### ISSUE TITLE
Significant difference occurs after adding some populations

### ISSUE THREAD

**Issue by wangzhx36** [StoreyLab/popkin#5]
Hi,
At the beginning, I merged data of several populations from one common species as input file for popkin, and the result looked reasonable. However, when I added some other populations from the same species, the kinships between individuals from the same population became bigger significantly than the previous values, and them looked unreasonable. I put the previous result and the current result here. For example, we can compare DSY population in previous result and MOPdsy population in current analysis, which are the same one population. I uesd the same script in these two analyses, and I have no idea about it. Could you help me?

![MOPpre](https://github.com/StoreyLab/popkin/assets/88385172/2338a0ff-b497-487c-a0ff-76ea2da4a384)
![MOPcur](https://github.com/StoreyLab/popkin/assets/88385172/af588a5c-8001-4bee-96aa-b19dd09dad45)

**Comment by alexviiia** [comment]
Hi, this is expected given the data.  Popkin treats the most distant relationship as zero kinship, so when you added more samples, one of them (the one shown at the very right/bottom of the last figure) was much more distant to the rest than any of the previous samples.  (Many of the new samples are also more distantly related to each other than any in the original subset, it is not explained entirely by that single sample.)  In terms of model parameters, all kinship coefficients are relative values in terms of a given Most Recent Common Ancestor (MRCA) population, and adding more samples has the potential to change the MRCA population, just as it happened here.  By itself this does not represent an issue with the popkin software (in other words, it is not a bug).

If you believe that the MRCA wasn't supposed to change given what you know about your data, then the issue could be quality control.  In other words, that extreme/outlier sample could have lower quality (higher missingness for array data, or lower coverage for sequencing data), or be the result of a batch effect (some other technical difference between the preparation/processing of that sample and the rest).  Popkin does not perform quality control, that should be done prior to analyzing your data with popkin.

Regardless, I can tell that removal of that single most extreme sample will still result in increased kinship values for the original subset (less extreme than right now, but still increased), because there are two more subpopulations that attain lower kinship values in the second plot than any of the original samples in that same plot.  Again, assuming there's nothing wrong with the data, the interpretation is simply that you are adding more distant populations so their overall MRCA population is now more ancient than the MRCA population of the original subset, and this is expected to increase all kinship values (to accommodate for the fact that there is now a more distant relationship than before).

**Comment by wangzhx36** [comment]
Hi, I have carefully read your explanations and suggestions, and I find them to be reasonable. Because some of the populations, although belonging to the same species, have already diverged significantly. When I ran popkin with fewer populations, I indeed observed a lower calculated kinship. Your response has been very helpful to me, and I appreciate your prompt reply.
